language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*

before_install: travis_retry composer require "illuminate/database:${ILLUMINATE_VERSION}" "illuminate/events:${ILLUMINATE_VERSION}" --no-update -v

install: travis_retry composer install --prefer-dist --no-interaction --no-suggest -v

before_script:
  - touch import.csv
  - touch import.json
  - chmod a+w -R import.csv import.json

script: vendor/bin/phpunit --debug -c phpunit.xml --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
